name: "go_builder"
mode: "dev"
port: 8888
db-type: "mysql"
version: "v0.0.1"

# jwt configuration
jwt:
  signing-key: q-cloud-ll
  expires-time: 7d
  buffer-time: 1d
  issuer: q-cloud-ll

cors:
  mode: strict-whitelist
  whitelist:
    - allow-origin: example1.com
      allow-headers: Content-Type,AccessToken,X-CSRF-Token, Authorization, Token,X-Token,X-User-Id
      allow-methods: POST, GET
      expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Content-Type

      allow-credentials: true # 布尔值
    - allow-origin: example2.com
      allow-headers: content-type
      allow-methods: GET, POST
      expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Content-Type
      allow-credentials: true # 布尔值

snowflake:
  start_time: "2020-07-01"
  machine_id: 1

log:
  level: "debug"
  filename: "go_builder.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host:
  port:
  user:
  password:
  dbname:
  max_open_conns:
  max_idle_conns:
redis:
  host:
  port:
  password: ""
  db: 0
  pool_size: 100